groups:
  - name: test
    tags:
      function: LinearFunction
    groups:
      - name: test3
    workers:
      - name: DefaultLinearFunctionMocker
        functionName: DefaultLinearFunction
        clientsName:
          #          - debug_client
          - prom
      - name: HalfLinearFunctionMocker
        functionName: StandardLinearFunction
        functionParams:
          slope: 0.5
          offsetX: 0
          offsetY: 0
        clientsName:
          #          - debug_client
          - prom
      - name: MinuteLinearFunctionMocker
        functionName: StandardLinearFunction
        functionParams:
          slope: 0.017
          offsetX: 0
          offsetY: 0
        clientsName:
          - prom
  - name: test2
    tags:
      v1: v2
clients:
  - name: debug_client
    type: StdoutClient
    params:
      STDOUT_FILE: STDOUT_FILE
  - name: prom
    type: PrometheusClient
    params:
      PROMETHEUS_OUTPUT_PORT: ":8080"
