Processors:
  - Name: test_processor
    Tags:
      v1: test1
    Functions:
      - Name: DefaultLinearFunction
        FuncName: Default test
      - FuncName: StandardLinearFunction test
        Name: StandardLinearFunction
        Params:
          slope: 0.5
          offsetX: 0
          offsetY: 0
    ClientNames:
      - debug_client
      - prom
clients:
  - name: debug_client
    type: StdoutClient
    params:
      STDOUT_FILE: STDOUT_FILE
  - name: prom
    type: PrometheusClient
    params:
      PROMETHEUS_OUTPUT_PORT: ":8080"