Processors:
  - Name: test-p
    Tags:
      v1: test1
    FunctionParamsList:
#      - Type: BaseLinearFunction
#        Name: Test1
      - Type: BaseLinearFunction
        Name: Test2
        Params:
          slope: 2.0
        KeyFunctions:
          x:
            type: ModularFunctionType
            Params:
              modular_unit: 10.0
            KeyFunctions:
              x:
                type: StartZeroFunc
                name: Start-Zero-func
#      - Type: StartZeroFuncType
#        Name: Start-Zero-func
    CronStr: "@every 5s"
    Clients:
      - debug_client
#      - influx-test-client
Clients:
  - name: debug_client
    type: StdoutClient
    params:
#      STDOUT_FILE: STDOUT_FILE # If you want to disable the debug_client, delete this line.
#  - name: influx-test-client
#    type: InfluxDBV1
#    params:
#      ServerURL: "http://127.0.0.1:8086"
#      Database: test
#      Table: test2
Application:
  ticker: 5
  port: ":3001"
  nodeId: local
  objectMockerConfig:
    enable: false
    host: "http://127.0.0.1:3000"
    syncInterval: "@every 5s"