Processors:
  - Name: metric_mocker_test_func_processor
    Tags:
      v1: test1
    FunctionParamsList:
      - Type: BaseLinearFunction
        Name: Test
    Clients:
      - debug_client
Clients:
  - name: debug_client
    type: StdoutClient
    params:
#      STDOUT_FILE: STDOUT_FILE # If you want to disable the debug_client, delete this line.
Application:
  ticker: 5
  objectClient:
    enable: false
    host: "http://object-mocker.mockers.svc:3000"